export const teachers = [
  {
    id: 1,
    employeeId: "EMP-1001",
    name: "Rahul Sharma",
    email: "rahul@college.edu",
    mobile: "9876543210",
    department: "Computer Science",
    status: "Active",
  },
  {
    id: 2,
    employeeId: "EMP-1002",
    name: "Priya Shah",
    email: "priya@college.edu",
    mobile: "9876543211",
    department: "Information Technology",
    status: "Active",
  },
  {
    id: 3,
    employeeId: "EMP-1003",
    name: "Amit Patel",
    email: "amit@college.edu",
    mobile: "9876543212",
    department: "Computer Science",
    status: "Active",
  },
  {
    id: 4,
    employeeId: "EMP-1004",
    name: "Sneha Mehta",
    email: "sneha@college.edu",
    mobile: "9876543213",
    department: "Mathematics",
    status: "Inactive",
  },
];

export const subjects = [
  {
    id: 1,
    code: "CS301",
    name: "Database Management Systems",
    semester: 3,
    credits: 4,
    type: "Theory",
    lecturesPerWeek: 4,
  },
  {
    id: 2,
    code: "CS302",
    name: "Object Oriented Programming",
    semester: 3,
    credits: 4,
    type: "Theory",
    lecturesPerWeek: 4,
  },
  {
    id: 3,
    code: "CS303",
    name: "Web Development",
    semester: 3,
    credits: 3,
    type: "Theory",
    lecturesPerWeek: 3,
  },
  {
    id: 4,
    code: "CS304",
    name: "Database Management Systems Lab",
    semester: 3,
    credits: 2,
    type: "Practical",
    lecturesPerWeek: 2,
  },
  {
    id: 5,
    code: "CS305",
    name: "Computer Networks",
    semester: 3,
    credits: 4,
    type: "Theory",
    lecturesPerWeek: 4,
  },
];

export const classrooms = [
  {
    id: 1,
    roomNumber: "301",
    building: "Main Building",
    capacity: 60,
    type: "Classroom",
    floor: 3,
    status: "Available",
  },
  {
    id: 2,
    roomNumber: "302",
    building: "Main Building",
    capacity: 60,
    type: "Classroom",
    floor: 3,
    status: "Available",
  },
  {
    id: 3,
    roomNumber: "LAB-1",
    building: "Science Block",
    capacity: 40,
    type: "Laboratory",
    floor: 1,
    status: "Available",
  },
  {
    id: 4,
    roomNumber: "LAB-2",
    building: "Science Block",
    capacity: 40,
    type: "Laboratory",
    floor: 1,
    status: "Maintenance",
  },
  {
    id: 5,
    roomNumber: "401",
    building: "Main Building",
    capacity: 100,
    type: "Classroom",
    floor: 4,
    status: "Available",
  },
];
